### Generating List of Guests

In [1]:
# generating random names

import random

first_names = ["Ali", "Zahra", "Reza", "Sara", "Mohammad", "Fatemeh", "Hossein", "Maryam", "Mehdi", "Narges", "Hamed", "Roya"]
last_names = ["Ahmadi", "Hosseini", "Karimi", "Rahimi", "Hashemi", "Ebrahimi", "Moradi", "Mohammadi", "Rostami", "Fazeli", "Hosseinzadeh", "Niknam"]
def generate_random_names(first_names, last_names, n):
    random_names = []
    while len(random_names) < 24:
        first_name = random.choice(first_names)
        last_name = random.choice(last_names)
        if not f"{first_name} {last_name}" in random_names:
            random_names.append(f"{first_name} {last_name}")
    return random_names

random_names = generate_random_names(first_names, last_names, 24)

for name in random_names:
    print(name)

Hossein Ebrahimi
Maryam Hosseinzadeh
Fatemeh Fazeli
Hamed Niknam
Reza Niknam
Roya Hashemi
Hossein Mohammadi
Roya Rostami
Reza Fazeli
Zahra Rahimi
Maryam Hosseini
Sara Mohammadi
Maryam Fazeli
Zahra Moradi
Narges Fazeli
Hamed Hosseinzadeh
Reza Hosseinzadeh
Maryam Niknam
Hossein Rostami
Narges Ahmadi
Zahra Ebrahimi
Hossein Hosseinzadeh
Fatemeh Moradi
Zahra Hosseinzadeh


### Generating random conflict binary matrix and conflict pairs

In [28]:
# generating random conflict binary matrix

import numpy as np

def generate_random_binary_matrix(size, num_ones):
    matrix = np.zeros((size, size), dtype=int)
    conflict_pairs = []
    possible_positions = [(i, j) for i in range(size) for j in range(size) if i != j]
    
    ones_positions = np.random.choice(len(possible_positions), num_ones, replace=False)
    
    for pos in ones_positions:
        i, j = possible_positions[pos]
        conflict_pairs.append((i, j))
        matrix[i, j] = 1
    
    return matrix, conflict_pairs

size = 24
num_ones = 40

conflict_matrix, conflict_pairs = generate_random_binary_matrix(size, num_ones)

print(conflict_matrix)
print(conflict_pairs)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0

### Suitable Arrangement: Deterministic approach

In [30]:
import random

# Checks if placing a guest at a specific position does not create conflicts with adjacent seats.
def is_safe(seating, row, col, guest, conflicts, rows, cols):
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < rows and 0 <= new_col < cols:
            if seating[new_row][new_col] in conflicts[guest]:
                print(f"Conflict between {guest} and {seating[new_row][new_col]} at ({new_row}, {new_col})")
                return False
    return True


# Recursively attempts to place guests in seats.
# Uses backtracking to ensure constraints are met.
# Shuffles the guests to provide a random assignment and potentially find a valid solution quicker.
def solve_seating(seating, guests, conflicts, row, col, rows, cols):
    if row == rows:
        return True
    if col == cols:
        return solve_seating(seating, guests, conflicts, row + 1, 0, rows, cols)

    random.shuffle(guests)  # Shuffle guests to get a random assignment
    for guest in guests:
        if is_safe(seating, row, col, guest, conflicts, rows, cols):
            seating[row][col] = guest
            if solve_seating(seating, guests, conflicts, row, col + 1, rows, cols):
                return True
            
    seating[row][col] = None
    return False


# Initializes the seating grid and the conflicts dictionary.
# Calls solve_seating to find a valid seating arrangement.
def arrange_seating(guests, conflict_pairs, rows, cols):
    seating = [[None for _ in range(cols)] for _ in range(rows)]
    conflicts = {guest: set() for guest in guests}
    for g1, g2 in conflict_pairs:
        conflicts[g1].add(g2)
        conflicts[g2].add(g1)
    print(conflicts)
    if solve_seating(seating, guests, conflicts, 0, 0, rows, cols):
        print(f"Seating arrangement found.{seating}")
        return seating
    else:
        return None

# Example usage
guests = list(range(0, 24))  # Guests labeled 0 to 23

rows, cols = 4, 6
seating_arrangement = arrange_seating(guests, conflict_pairs, rows, cols)

print("***Seating Arrangement***")
if seating_arrangement:
    for row in seating_arrangement:
        print(row)
else:
    print("No valid seating arrangement found.")


{0: {9}, 1: {17, 5, 6}, 2: {5, 21}, 3: {8, 12, 13, 18, 22}, 4: {17}, 5: {1, 2, 9, 12, 20, 22}, 6: {1, 14, 16, 17, 19, 20, 22}, 7: {16, 9}, 8: {16, 3, 21, 22}, 9: {0, 5, 7, 20, 22}, 10: set(), 11: {14, 23}, 12: {13, 3, 5}, 13: {3, 19, 12, 23}, 14: {11, 6}, 15: {17, 21}, 16: {8, 21, 6, 7}, 17: {1, 4, 6, 15}, 18: {3}, 19: {20, 13, 6}, 20: {9, 19, 5, 6}, 21: {16, 8, 2, 15}, 22: {3, 5, 6, 8, 9, 23}, 23: {11, 13, 22}}
Conflict between 6 and 20 at (0, 0)
Conflict between 5 and 9 at (0, 3)
Conflict between 5 and 22 at (1, 1)
Conflict between 17 and 4 at (0, 2)
Conflict between 6 and 22 at (1, 1)
Conflict between 17 and 6 at (1, 3)
Conflict between 21 and 15 at (1, 5)
Conflict between 3 and 22 at (3, 0)
Seating arrangement found.[[20, 0, 4, 9, 19, 2], [11, 22, 10, 6, 8, 15], [18, 1, 18, 18, 2, 6], [22, 20, 16, 2, 16, 11]]
***Seating Arrangement***
[20, 0, 4, 9, 19, 2]
[11, 22, 10, 6, 8, 15]
[18, 1, 18, 18, 2, 6]
[22, 20, 16, 2, 16, 11]
