### Generating List of Guests

In [1]:
# generating random names

import random

first_names = ["Ali", "Zahra", "Reza", "Sara", "Mohammad", "Fatemeh", "Hossein", "Maryam", "Mehdi", "Narges", "Hamed", "Roya"]
last_names = ["Ahmadi", "Hosseini", "Karimi", "Rahimi", "Hashemi", "Ebrahimi", "Moradi", "Mohammadi", "Rostami", "Fazeli", "Hosseinzadeh", "Niknam"]
def generate_random_names(first_names, last_names, n):
    random_names = []
    while len(random_names) < 24:
        first_name = random.choice(first_names)
        last_name = random.choice(last_names)
        if not f"{first_name} {last_name}" in random_names:
            random_names.append(f"{first_name} {last_name}")
    return random_names

random_names = generate_random_names(first_names, last_names, 24)

for name in random_names:
    print(name)

Narges Moradi
Hossein Hosseini
Zahra Hosseinzadeh
Fatemeh Rostami
Sara Rahimi
Reza Rahimi
Reza Niknam
Maryam Rahimi
Zahra Karimi
Fatemeh Moradi
Hossein Ebrahimi
Roya Karimi
Hossein Ahmadi
Zahra Niknam
Narges Hashemi
Hossein Niknam
Maryam Ahmadi
Hamed Ahmadi
Mehdi Rostami
Fatemeh Hosseinzadeh
Maryam Ebrahimi
Fatemeh Ebrahimi
Ali Hosseini
Roya Niknam


### Generating random conflict binary matrix and conflict pairs

In [2]:
# generating random conflict binary matrix

import numpy as np

def generate_random_binary_matrix(size, num_ones):
    matrix = np.zeros((size, size), dtype=int)
    conflict_pairs = []
    possible_positions = [(i, j) for i in range(size) for j in range(size) if i != j]
    
    ones_positions = np.random.choice(len(possible_positions), num_ones, replace=False)
    
    for pos in ones_positions:
        i, j = possible_positions[pos]
        conflict_pairs.append((i, j))
        matrix[i, j] = 1
    
    return matrix, conflict_pairs

size = 24
num_ones = 40

conflict_matrix, conflict_pairs = generate_random_binary_matrix(size, num_ones)

print(conflict_matrix)
print(conflict_pairs)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0

### Suitable Arrangement: Deterministic approach

In [3]:
import random

# Checks if placing a guest at a specific position does not create conflicts with adjacent seats.
def is_safe(seating, row, col, guest, conflicts, rows, cols):
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < rows and 0 <= new_col < cols:
            if seating[new_row][new_col] in conflicts[guest]:
                print(f"Conflict between {guest} and {seating[new_row][new_col]} at ({new_row}, {new_col})")
                return False
    return True


# Recursively attempts to place guests in seats.
# Uses backtracking to ensure constraints are met.
# Shuffles the guests to provide a random assignment and potentially find a valid solution quicker.
def solve_seating(seating, guests, conflicts, row, col, rows, cols):
    if row == rows:
        return True
    if col == cols:
        return solve_seating(seating, guests, conflicts, row + 1, 0, rows, cols)

    random.shuffle(guests)  # Shuffle guests to get a random assignment
    for guest in guests:
        if is_safe(seating, row, col, guest, conflicts, rows, cols):
            seating[row][col] = guest
            if solve_seating(seating, guests, conflicts, row, col + 1, rows, cols):
                return True
            
    seating[row][col] = None
    return False


# Initializes the seating grid and the conflicts dictionary.
# Calls solve_seating to find a valid seating arrangement.
def arrange_seating(guests, conflict_pairs, rows, cols):
    seating = [[None for _ in range(cols)] for _ in range(rows)]
    conflicts = {guest: set() for guest in guests}
    for g1, g2 in conflict_pairs:
        conflicts[g1].add(g2)
        conflicts[g2].add(g1)
    print(conflicts)
    if solve_seating(seating, guests, conflicts, 0, 0, rows, cols):
        print(f"Seating arrangement found.{seating}")
        return seating
    else:
        return None

# Example usage
guests = list(range(0, 24))  # Guests labeled 0 to 23

rows, cols = 4, 6
seating_arrangement = arrange_seating(guests, conflict_pairs, rows, cols)

print("***Seating Arrangement***")
if seating_arrangement:
    for row in seating_arrangement:
        print(row)
else:
    print("No valid seating arrangement found.")


{0: {3, 19, 15}, 1: {11, 19, 12}, 2: {3, 7, 9, 12, 13, 20}, 3: {0, 2, 8, 10, 11, 15, 20}, 4: {16, 17, 23}, 5: {16, 11, 14}, 6: {12, 14}, 7: {16, 2, 15}, 8: {16, 3, 22}, 9: {2, 22}, 10: {3, 22}, 11: {1, 3, 5, 15, 18}, 12: {1, 2, 6}, 13: {2, 21}, 14: {5, 6}, 15: {0, 3, 7, 11, 17, 19}, 16: {8, 4, 5, 7}, 17: {19, 4, 23, 15}, 18: {11}, 19: {0, 1, 15, 17, 20}, 20: {3, 2, 19}, 21: {13}, 22: {8, 9, 10}, 23: {17, 4}}
Seating arrangement found.[[18, 5, 6, 7, 14, 4], [17, 10, 15, 1, 9, 13], [18, 17, 18, 2, 1, 8], [17, 5, 23, 22, 14, 0]]
***Seating Arrangement***
[18, 5, 6, 7, 14, 4]
[17, 10, 15, 1, 9, 13]
[18, 17, 18, 2, 1, 8]
[17, 5, 23, 22, 14, 0]


### Sequence-to-Sequence Neural Network Approach for Seating Arrangement

#### Problem Definition
We aim to arrange 24 guests in a 4x6 grid (24 seats) such that guests with conflicts do not sit next to each other either horizontally or vertically. There are 40 pairs of guests with conflicts.

#### Approach
We will solve this problem using a neural network in a sequence-to-sequence manner with fully connected layers.

#### Key Concepts
Input and Output Sequences:

Input: A sequence representing the guests already seated.
Output: The next guest to be seated, ensuring minimum conflicts with adjacent guests.
Flattening the Matrix:

The seating arrangement matrix will be flattened into a single-dimensional array.
#### Conflict Checking:

We will ensure that the guest to be seated does not have conflicts with adjacent seats both horizontally and vertically.
#### Neural Network Architecture
Input Layer: Takes the current sequence of seated guests (flattened matrix).
Hidden Layers: Fully connected layers with ReLU activation.
Output Layer: Predicts the next guest to be seated.
Loss Function
Masked Cross-Entropy Loss: Ensures that only valid guests (those without conflicts) are considered during training.
#### Training Data
We will generate training data by simulating valid seating arrangements.

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np

# Define the seating grid dimensions
rows, cols = 4, 6
total_seats = rows * cols

# Define the guest list and conflict pairs
guests = list(range(0, 24))  # Guests labeled 0 to 23
size = 24
num_ones = 40
_, conflict_pairs = generate_random_binary_matrix(size, num_ones)


# Convert conflict pairs to a dictionary for quick lookup
conflicts = {guest: set() for guest in guests}
for g1, g2 in conflict_pairs:
    conflicts[g1].add(g2)
    conflicts[g2].add(g1)


In [7]:
# Neural network model
class SeatingNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SeatingNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize the model, loss function, and optimizer
input_size = total_seats
hidden_size = 128
output_size = len(guests)
model = SeatingNN(input_size, hidden_size, output_size)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [9]:
# Function to generate a training example
def generate_example():
    seating = [0] * total_seats
    sequence = []
    for i in range(total_seats):
        available_guests = [g for g in guests if g not in sequence and
                            all(g not in conflicts[sequence[j]] for j in range(max(0, i-cols), i))]
        if not available_guests:
            break
        next_guest = random.choice(available_guests)
        sequence.append(next_guest)
        seating[i] = next_guest
    return seating, sequence


In [10]:
a, b = generate_example()
print(a)
print(b)

[6, 21, 18, 11, 14, 22, 10, 23, 15, 7, 13, 16, 1, 20, 3, 5, 8, 0, 0, 0, 0, 0, 0, 0]
[6, 21, 18, 11, 14, 22, 10, 23, 15, 7, 13, 16, 1, 20, 3, 5, 8]


In [14]:
# Training loop
epochs = 100
for epoch in range(epochs):
    seating, sequence = generate_example()
    for i in range(len(sequence) - 1):
        input_seq = torch.tensor(seating[:i+1] + [0] * (total_seats - (i+1)), dtype=torch.float32)
        print(f"input sequence: {input_seq}")
        target = torch.tensor(guests.index(sequence[i+1]))
        print(f"target sequence: {target}")
        optimizer.zero_grad()
        output = model(input_seq)
        print(f"output sequence: {output}")
        loss = criterion(output.view(1, -1), target.view(1))
        print(f"loss: {loss}")
        loss.backward()
        optimizer.step()


input sequence: tensor([3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
target sequence: 23
output sequence: tensor([-1.9617e-01, -2.5205e-02, -1.0440e-01, -1.9903e-01, -2.2142e-01,
        -1.3029e-01, -2.4875e-03, -6.1035e-02, -8.5161e-02, -1.9149e-01,
         2.0315e-02, -1.4687e-01,  4.1141e-04, -1.4999e-01, -4.4932e-02,
        -6.8624e-02, -9.9201e-02, -4.9033e-01,  6.5991e-02, -1.8054e-01,
        -3.4856e-02, -1.4880e-01, -3.8430e-02, -1.2004e-01],
       grad_fn=<ViewBackward0>)
loss: 3.193268060684204
input sequence: tensor([ 3., 23.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
target sequence: 1
output sequence: tensor([-6.6321e-01, -6.1243e-01, -1.8481e-01, -2.3472e-01, -6.0542e-01,
        -9.7799e-01,  1.0059e-03, -3.3341e-01, -4.5366e-01, -8.2525e-01,
        -6.4324e-01, -2.6879e-01, -4.6556e-01, -5.0785e-01, -5.9622e-01,
        -6.4086e-

In [15]:
# Function to predict the next guest
def predict_next_guest(seating):
    input_seq = torch.tensor(seating, dtype=torch.float32)
    with torch.no_grad():
        output = model(input_seq)
    probs = torch.softmax(output, dim=0)
    return torch.argmax(probs).item()

# Test the model with a new seating arrangement
seating = [0] * total_seats
for i in range(total_seats):
    next_guest = predict_next_guest(seating)
    if next_guest not in seating:
        seating[i] = next_guest
    else:
        break

print("Seating arrangement:")
for i in range(rows):
    print(seating[i*cols:(i+1)*cols])

Seating arrangement:
[15, 22, 6, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
