### Generating List of Guests

In [2]:
# generating random names

import random

first_names = ["Ali", "Zahra", "Reza", "Sara", "Mohammad", "Fatemeh", "Hossein", "Maryam", "Mehdi", "Narges", "Hamed", "Roya"]
last_names = ["Ahmadi", "Hosseini", "Karimi", "Rahimi", "Hashemi", "Ebrahimi", "Moradi", "Mohammadi", "Rostami", "Fazeli", "Hosseinzadeh", "Niknam"]
def generate_random_names(first_names, last_names, n):
    random_names = []
    while len(random_names) < 24:
        first_name = random.choice(first_names)
        last_name = random.choice(last_names)
        if not f"{first_name} {last_name}" in random_names:
            random_names.append(f"{first_name} {last_name}")
    return random_names

random_names = generate_random_names(first_names, last_names, 24)

for name in random_names:
    print(name)

Hamed Karimi
Hossein Hosseinzadeh
Hossein Mohammadi
Narges Moradi
Hossein Moradi
Maryam Moradi
Fatemeh Hosseinzadeh
Reza Niknam
Sara Karimi
Ali Moradi
Roya Fazeli
Narges Mohammadi
Zahra Karimi
Mehdi Hosseini
Narges Hosseinzadeh
Narges Hashemi
Reza Rostami
Hamed Hashemi
Ali Hosseinzadeh
Maryam Niknam
Reza Ahmadi
Mehdi Rostami
Zahra Hosseinzadeh
Hamed Rahimi


### Generating random conflict binary matrix and conflict pairs

In [3]:
# generating random conflict binary matrix

import numpy as np

def generate_random_binary_matrix(size, num_ones):
    matrix = np.zeros((size, size), dtype=int)
    conflict_pairs = []
    possible_positions = [(i, j) for i in range(size) for j in range(size) if i != j]
    
    ones_positions = np.random.choice(len(possible_positions), num_ones, replace=False)
    
    for pos in ones_positions:
        i, j = possible_positions[pos]
        conflict_pairs.append((i, j))
        matrix[i, j] = 1
    
    return matrix, conflict_pairs

size = 24
num_ones = 40

conflict_matrix, conflict_pairs = generate_random_binary_matrix(size, num_ones)

print(conflict_matrix)
print(conflict_pairs)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

### Suitable Arrangement: Deterministic approach

In [4]:
import random

# Checks if placing a guest at a specific position does not create conflicts with adjacent seats.
def is_safe(seating, row, col, guest, conflicts, rows, cols):
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < rows and 0 <= new_col < cols:
            if seating[new_row][new_col] in conflicts[guest]:
                print(f"Conflict between {guest} and {seating[new_row][new_col]} at ({new_row}, {new_col})")
                return False
    return True


# Recursively attempts to place guests in seats.
# Uses backtracking to ensure constraints are met.
# Shuffles the guests to provide a random assignment and potentially find a valid solution quicker.
def solve_seating(seating, guests, conflicts, row, col, rows, cols):
    if row == rows:
        return True
    if col == cols:
        return solve_seating(seating, guests, conflicts, row + 1, 0, rows, cols)

    random.shuffle(guests)  # Shuffle guests to get a random assignment
    for guest in guests:
        if is_safe(seating, row, col, guest, conflicts, rows, cols):
            seating[row][col] = guest
            if solve_seating(seating, guests, conflicts, row, col + 1, rows, cols):
                return True
            
    seating[row][col] = None
    return False


# Initializes the seating grid and the conflicts dictionary.
# Calls solve_seating to find a valid seating arrangement.
def arrange_seating(guests, conflict_pairs, rows, cols):
    seating = [[None for _ in range(cols)] for _ in range(rows)]
    conflicts = {guest: set() for guest in guests}
    for g1, g2 in conflict_pairs:
        conflicts[g1].add(g2)
        conflicts[g2].add(g1)
    print(conflicts)
    if solve_seating(seating, guests, conflicts, 0, 0, rows, cols):
        print(f"Seating arrangement found.{seating}")
        return seating
    else:
        return None

# Example usage
guests = list(range(0, 24))  # Guests labeled 0 to 23

rows, cols = 4, 6
seating_arrangement = arrange_seating(guests, conflict_pairs, rows, cols)

print("***Seating Arrangement***")
if seating_arrangement:
    for row in seating_arrangement:
        print(row)
else:
    print("No valid seating arrangement found.")


{0: {2, 7, 12, 15}, 1: {2, 3}, 2: {0, 1, 7, 9, 15}, 3: {1, 5, 9, 15, 21}, 4: {23}, 5: {17, 3, 20, 23}, 6: {11, 13}, 7: {0, 2, 20}, 8: {16, 18}, 9: {17, 2, 3}, 10: {19, 23}, 11: {19, 12, 6}, 12: {0, 17, 11, 20}, 13: {16, 20, 21, 6}, 14: {19, 20, 23}, 15: {0, 2, 3, 19, 20}, 16: {8, 13}, 17: {9, 12, 5}, 18: {8}, 19: {10, 11, 14, 15}, 20: {5, 7, 12, 13, 14, 15}, 21: {3, 13}, 22: set(), 23: {10, 4, 5, 14}}
Conflict between 10 and 23 at (0, 4)
Conflict between 2 and 9 at (0, 0)
Conflict between 6 and 11 at (1, 0)
Conflict between 19 and 11 at (1, 1)
Conflict between 23 and 14 at (1, 2)
Conflict between 17 and 12 at (3, 0)
Conflict between 11 and 12 at (3, 0)
Conflict between 10 and 23 at (2, 3)
Conflict between 20 and 12 at (3, 3)
Conflict between 5 and 17 at (2, 5)
Conflict between 20 and 15 at (3, 4)
Conflict between 2 and 15 at (3, 4)
Seating arrangement found.[[9, 7, 15, 11, 23, 12], [11, 11, 14, 21, 16, 16], [9, 13, 1, 23, 11, 17], [12, 18, 5, 12, 15, 23]]
***Seating Arrangement***
[9, 

### Sequence-to-Sequence Neural Network Approach for Seating Arrangement

#### Problem Definition
We aim to arrange 24 guests in a 4x6 grid (24 seats) such that guests with conflicts do not sit next to each other either horizontally or vertically. There are 40 pairs of guests with conflicts.

#### Approach
We will solve this problem using a neural network in a sequence-to-sequence manner with fully connected layers.

#### Key Concepts
Input and Output Sequences:

Input: A sequence representing the guests already seated.
Output: The next guest to be seated, ensuring minimum conflicts with adjacent guests.
Flattening the Matrix:

The seating arrangement matrix will be flattened into a single-dimensional array.
#### Conflict Checking:

We will ensure that the guest to be seated does not have conflicts with adjacent seats both horizontally and vertically.
#### Neural Network Architecture
Input Layer: Takes the current sequence of seated guests (flattened matrix).
Hidden Layers: Fully connected layers with ReLU activation.
Output Layer: Predicts the next guest to be seated.
Loss Function
Masked Cross-Entropy Loss: Ensures that only valid guests (those without conflicts) are considered during training.
#### Training Data
We will generate training data by simulating valid seating arrangements.

In [5]:
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np

# Define the seating grid dimensions
rows, cols = 4, 6
total_seats = rows * cols

# Define the guest list and conflict pairs
guests = list(range(0, 24))  # Guests labeled 0 to 23
size = 24
num_ones = 40
_, conflict_pairs = generate_random_binary_matrix(size, num_ones)


# Convert conflict pairs to a dictionary for quick lookup
conflicts = {guest: set() for guest in guests}
for g1, g2 in conflict_pairs:
    conflicts[g1].add(g2)
    conflicts[g2].add(g1)


In [53]:
# Neural network model
class SeatingNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SeatingNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize the model, loss function, and optimizer
input_size = total_seats
hidden_size = 128
output_size = len(guests)
model = SeatingNN(input_size, hidden_size, output_size)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [54]:
# Function to generate a training example
def generate_example():
    seating = [0] * total_seats
    sequence = []
    for i in range(total_seats):
        available_guests = [g for g in guests if g not in sequence and
                            all(g not in conflicts[sequence[j]] for j in range(max(0, i-cols), i))]
        if not available_guests:
            break
        next_guest = random.choice(available_guests)
        sequence.append(next_guest)
        seating[i] = next_guest
    return seating, sequence


In [55]:
import random
import torch

# Number of examples to generate
num_examples = 1000

# Storage for seating and sequences
data = []

# Generate all data examples
for _ in range(num_examples):
    seating, sequence = generate_example()
    data.append((seating, sequence))




# Parameters
batch_size = 32
epochs = 500

# Function to create a batch from the data
def create_batches(data, batch_size):
    batches = []
    for batch_start in range(0, len(data), batch_size):
        batch = data[batch_start:batch_start + batch_size]
        input_batch = []
        target_batch = []
        for seating, sequence in batch:
            for i in range(len(sequence) - 1):
                input_seq = seating[:i+1] + [0] * (total_seats - (i+1))
                target = guests.index(sequence[i+1])
                input_batch.append(input_seq)
                target_batch.append(target)
        batches.append((torch.tensor(input_batch, dtype=torch.float32), torch.tensor(target_batch)))
    return batches

# Training loop
for epoch in range(epochs):
    total_loss = 0
    random.shuffle(data)  # Shuffle the data at the beginning of each epoch
    
    # Create batches from the data
    batches = create_batches(data, batch_size)
    
    # Process each batch
    for input_batch, target_batch in batches:
        optimizer.zero_grad()
        outputs = model(input_batch)
        loss = criterion(outputs, target_batch)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
    
    avg_loss = total_loss / len(batches)
    print(f"Epoch {epoch + 1}/{epochs}, Loss: {avg_loss}")




Epoch 1/500, Loss: 3.171452395617962
Epoch 2/500, Loss: 3.115494132041931
Epoch 3/500, Loss: 3.1002166718244553
Epoch 4/500, Loss: 3.089189261198044
Epoch 5/500, Loss: 3.075389325618744
Epoch 6/500, Loss: 3.0636216923594475
Epoch 7/500, Loss: 3.0544644445180893
Epoch 8/500, Loss: 3.04524876922369
Epoch 9/500, Loss: 3.0331378132104874
Epoch 10/500, Loss: 3.023331828415394
Epoch 11/500, Loss: 3.0144594609737396
Epoch 12/500, Loss: 3.002711035311222
Epoch 13/500, Loss: 2.9911215528845787
Epoch 14/500, Loss: 2.9801390767097473
Epoch 15/500, Loss: 2.972341373562813
Epoch 16/500, Loss: 2.959844321012497
Epoch 17/500, Loss: 2.94791042804718
Epoch 18/500, Loss: 2.9408200532197952
Epoch 19/500, Loss: 2.9315019324421883
Epoch 20/500, Loss: 2.92066340893507
Epoch 21/500, Loss: 2.910762496292591
Epoch 22/500, Loss: 2.900636665523052
Epoch 23/500, Loss: 2.8863994628190994
Epoch 24/500, Loss: 2.8844259530305862
Epoch 25/500, Loss: 2.8705825433135033
Epoch 26/500, Loss: 2.8604059517383575
Epoch 27/50

In [57]:
def predict_next_guest(seating):
    # Ensure input tensor has the correct shape
    input_seq = torch.tensor(seating + [0] * (total_seats - len(seating)), dtype=torch.float32)
    input_seq = input_seq.unsqueeze(0)  # Add batch dimension
    with torch.no_grad():
        output = model(input_seq)
    probs = torch.softmax(output.squeeze(), dim=0)
    return torch.argmax(probs).item()



# Test the model with a new seating arrangement
seating = [0] * total_seats
for i in range(total_seats):
    next_guest = predict_next_guest(seating[:i])  # Pass the current seating arrangement
    if next_guest not in seating:
        seating[i] = next_guest
    else:
        break

print("Seating arrangement:")
for i in range(rows):
    print(seating[i*cols:(i+1)*cols])



Seating arrangement:
[6, 14, 22, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]


In [4]:
# approach 2

import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np


# Utility function to check conflicts
def has_conflict(seating, guest, index, rows, cols, conflicts):
    row, col = divmod(index, cols)
    for r, c in [(row-1, col), (row+1, col), (row, col-1), (row, col+1)]:
        if 0 <= r < rows and 0 <= c < cols:
            if seating[r*cols + c] in conflicts[guest]:
                return True
    return False

# Encoder-Decoder with Attention Model
class Encoder(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(Encoder, self).__init__()
        self.hidden_size = hidden_size
        self.embedding = nn.Embedding(input_size, hidden_size)
        self.lstm = nn.LSTM(hidden_size, hidden_size)

    def forward(self, input, hidden):
        embedded = self.embedding(input).view(1, 1, -1)
        output, hidden = self.lstm(embedded, hidden)
        return output, hidden

    def initHidden(self):
        return (torch.zeros(1, 1, self.hidden_size),
                torch.zeros(1, 1, self.hidden_size))

class AttentionDecoder(nn.Module):
    def __init__(self, hidden_size, output_size, dropout_p=0.1, max_length=total_seats):
        super(AttentionDecoder, self).__init__()
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.dropout_p = dropout_p
        self.max_length = max_length

        self.embedding = nn.Embedding(self.output_size, self.hidden_size)
        self.attn = nn.Linear(self.hidden_size * 2, self.max_length)
        self.attn_combine = nn.Linear(self.hidden_size * 2, self.hidden_size)
        self.dropout = nn.Dropout(self.dropout_p)
        self.lstm = nn.LSTM(self.hidden_size, self.hidden_size)
        self.out = nn.Linear(self.hidden_size, self.output_size)

    def forward(self, input, hidden, encoder_outputs):
        embedded = self.embedding(input).view(1, 1, -1)
        embedded = self.dropout(embedded)

        attn_weights = torch.softmax(
            self.attn(torch.cat((embedded[0], hidden[0][0]), 1)), dim=1)
        attn_applied = torch.bmm(attn_weights.unsqueeze(0),
                                 encoder_outputs.unsqueeze(0))

        output = torch.cat((embedded[0], attn_applied[0]), 1)
        output = self.attn_combine(output).unsqueeze(0)

        output = torch.relu(output)
        output, hidden = self.lstm(output, hidden)

        output = torch.softmax(self.out(output[0]), dim=1)
        return output, hidden, attn_weights

    def initHidden(self):
        return (torch.zeros(1, 1, self.hidden_size),
                torch.zeros(1, 1, self.hidden_size))

# Function to generate a training example
def generate_example():
    seating = [0] * total_seats
    sequence = []
    for i in range(total_seats):
        available_guests = [g for g in guests if g not in sequence and
                            not has_conflict(seating, g, i, rows, cols, conflicts)]
        if not available_guests:
            break
        next_guest = random.choice(available_guests)
        sequence.append(next_guest)
        seating[i] = next_guest
    return seating, sequence

# Training the model
hidden_size = 256
encoder = Encoder(len(guests) + 1, hidden_size)
attn_decoder = AttentionDecoder(hidden_size, len(guests) + 1, dropout_p=0.1)

encoder_optimizer = optim.Adam(encoder.parameters(), lr=0.001)
decoder_optimizer = optim.Adam(attn_decoder.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

def train(input_tensor, target_tensor, encoder, decoder, encoder_optimizer, decoder_optimizer, criterion, max_length=total_seats):
    encoder_hidden = encoder.initHidden()

    encoder_optimizer.zero_grad()
    decoder_optimizer.zero_grad()

    input_length = input_tensor.size(0)
    target_length = target_tensor.size(0)

    encoder_outputs = torch.zeros(max_length, encoder.hidden_size)

    loss = 0

    for ei in range(input_length):
        encoder_output, encoder_hidden = encoder(input_tensor[ei], encoder_hidden)
        encoder_outputs[ei] = encoder_output[0, 0]

    decoder_input = torch.tensor([[0]])  # Start token

    decoder_hidden = encoder_hidden

    for di in range(target_length):
        decoder_output, decoder_hidden, decoder_attention = decoder(
            decoder_input, decoder_hidden, encoder_outputs)
        topv, topi = decoder_output.topk(1)
        decoder_input = topi.squeeze().detach()  # Teacher forcing

        loss += criterion(decoder_output, target_tensor[di].view(1))
        if decoder_input.item() == 0:
            break

    loss.backward()

    encoder_optimizer.step()
    decoder_optimizer.step()

    return loss.item() / target_length

def train_iters(encoder, decoder, n_iters, print_every=1000, learning_rate=0.01):
    for iter in range(1, n_iters + 1):
        seating, sequence = generate_example()
        input_tensor = torch.tensor(seating, dtype=torch.long).view(-1, 1)
        target_tensor = torch.tensor(sequence, dtype=torch.long).view(-1, 1)

        loss = train(input_tensor, target_tensor, encoder,
                     decoder, encoder_optimizer, decoder_optimizer, criterion)

        if iter % print_every == 0:
            print(f'Iteration {iter}, Loss: {loss:.4f}')

train_iters(encoder, attn_decoder, 10000)

# Function to predict the next guest
def predict_next_guest(seating, encoder, decoder, max_length=total_seats):
    with torch.no_grad():
        input_tensor = torch.tensor(seating, dtype=torch.long).view(-1, 1)
        input_length = input_tensor.size()[0]
        encoder_hidden = encoder.initHidden()

        encoder_outputs = torch.zeros(max_length, encoder.hidden_size)

        for ei in range(input_length):
            encoder_output, encoder_hidden = encoder(input_tensor[ei], encoder_hidden)
            encoder_outputs[ei] += encoder_output[0, 0]

        decoder_input = torch.tensor([[0]])  # Start token
        decoder_hidden = encoder_hidden

        decoded_words = []

        for di in range(max_length):
            decoder_output, decoder_hidden, decoder_attention = decoder(
                decoder_input, decoder_hidden, encoder_outputs)
            topv, topi = decoder_output.data.topk(1)
            if topi.item() == 0:
                break
            else:
                decoded_words.append(topi.item())

            decoder_input = topi.squeeze().detach()

        return decoded_words

# Test the model with a new seating arrangement
seating = [0] * total_seats
for i in range(total_seats):
    next_guest = predict_next_guest(seating, encoder, attn_decoder)
    if next_guest and next_guest[0] not in seating:
        seating[i] = next_guest[0]
    else:
        break

print("Seating arrangement:")
for i in range(rows):
    print(seating[i*cols:(i+1)*cols])



Iteration 1000, Loss: 3.1715
Iteration 2000, Loss: 3.1534
Iteration 3000, Loss: 3.0998
Iteration 4000, Loss: 3.0868
Iteration 5000, Loss: 3.0701
Iteration 6000, Loss: 3.0448
Iteration 7000, Loss: 3.0657
Iteration 8000, Loss: 3.0787
Iteration 9000, Loss: 3.0303
Iteration 10000, Loss: 3.0306
Seating arrangement:
[14, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
